# ============================== Filebeat inputs ==============================
name: filebeat

# # Assume that monitored service will be deployed with Docker.
# # This is for future uses.
# filebeat.autodiscover:
#   providers:
#     - type: docker
#       templates:
#         - condition:
#             contains:
#               docker.container.image: foo
#           config:
#             - type: container
#               paths:
#                 - /var/lib/docker/containers/${data.docker.container.id}/*.log
#               exclude_lines: ["^\\s+[\\-`('.|_]"]  # drop asciiart lines

# Crawl logs inside filebeat container.
filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    # REQUIRED: Change the path to your logs:
    - /var/log/*.log

# ============================== Filebeat modules ==============================
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# ================================== Outputs ===================================
# ------------------------------ Logstash Output -------------------------------
output.logstash:
  hosts: ["10.20.1.3:5044"]
  loadbalance: true